// GENERATED by tools/build-rpg-data.py — do not edit by hand.
window.RPG_DATA = {
  "publications": [
    {
      "authorsShort": "George et al.",
      "nAuthors": 10,
      "year": 2026,
      "title": "Pregnancy and postpartum nutritional wants and needs in athletes: a cross-sectional survey in the United Kingdom and Republic of Ireland",
      "journal": "Performance Nutrition",
      "doi": "10.1186/s44410-026-00030-0"
    },
    {
      "authorsShort": "Camp et al.",
      "nAuthors": 5,
      "year": 2025,
      "title": "Do athletes cook? A systematic scoping review of culinary nutrition in athletes",
      "journal": "Nutrition Bulletin",
      "doi": "10.1111/nbu.70012"
    },
    {
      "authorsShort": "Renard et al.",
      "nAuthors": 8,
      "year": 2025,
      "title": "Domestic cooking and food behaviours during the COVID-19 pandemic and the cost-of-living crisis: A scoping review",
      "journal": "Appetite",
      "doi": "10.1016/j.appet.2025.108311"
    },
    {
      "authorsShort": "Buckley et al.",
      "nAuthors": 28,
      "year": 2024,
      "title": "How transparent are quantitative studies in contemporary technology education research? Instrument development and analysis",
      "journal": "International Journal of Technology and Design Education",
      "doi": "10.1007/s10798-023-09827-9"
    },
    {
      "authorsShort": "Renard et al.",
      "nAuthors": 5,
      "year": 2023,
      "title": "Cooking and food skills confidence of team sport athletes in Ireland",
      "journal": "Nutrition Bulletin",
      "doi": "10.1111/nbu.12625"
    },
    {
      "authorsShort": "Taim et al.",
      "nAuthors": 6,
      "year": 2023,
      "title": "The prevalence of menstrual cycle disorders and menstrual cycle-related symptoms in female athletes: A systematic literature review",
      "journal": "Sports Medicine",
      "doi": "10.1007/s40279-023-01871-8"
    },
    {
      "authorsShort": "Buckley et al.",
      "nAuthors": 39,
      "year": 2022,
      "title": "An assessment of the transparency of contemporary technology education research employing interview-based methodologies",
      "journal": "International Journal of Technology and Design Education",
      "doi": "10.1007/s10798-021-09695-1"
    },
    {
      "authorsShort": "Renard et al.",
      "nAuthors": 4,
      "year": 2022,
      "title": "Evaluation of nutrition knowledge in elite and sub-elite Gaelic football players",
      "journal": "Science and Medicine in Football",
      "doi": "10.1080/24733938.2021.1883195"
    },
    {
      "authorsShort": "Renard et al.",
      "nAuthors": 4,
      "year": 2021,
      "title": "How does the dietary intake of female field-based team sport athletes compare to dietary recommendations for health and performance? A systematic literature review",
      "journal": "Nutrients",
      "doi": "10.3390/nu13041235"
    },
    {
      "authorsShort": "Renard et al.",
      "nAuthors": 4,
      "year": 2020,
      "title": "Evaluation of nutrition knowledge in female Gaelic games players",
      "journal": "Sports",
      "doi": "10.3390/sports8120154"
    },
    {
      "authorsShort": "Ó Catháin et al.",
      "nAuthors": 4,
      "year": 2020,
      "title": "Dietary intake of Gaelic football players during game preparation and recovery",
      "journal": "Sports",
      "doi": "10.3390/sports8050062"
    }
  ],
  "skills": [
    {
      "name": "Statistical modelling",
      "items": [
        "Linear mixed-effects models (random intercepts and slopes)",
        "Mundlak within/between decomposition",
        "fixed-effects OLS with cluster-robust standard errors",
        "piecewise and segmented threshold models with AIC-based knot search"
      ],
      "total": 12
    },
    {
      "name": "Evidence synthesis",
      "items": [
        "PRISMA 2020 and PRISMA-P",
        "PROSPERO registration (four records)",
        "systematic and scoping review methodology",
        "MMAT"
      ],
      "total": 6
    },
    {
      "name": "Programming & tools",
      "items": [
        "Python (statsmodels, pandas, NumPy, seaborn, matplotlib, python-docx, PyMuPDF)",
        "R (ggplot2, tidyverse)",
        "SPSS",
        "Git and GitHub"
      ],
      "total": 8
    },
    {
      "name": "Physiological measurement",
      "items": [
        "Wearable and in-home environmental monitoring (temperature, humidity, CO₂, particulates)",
        "actigraphy and sleep outcome derivation (TST, WASO, sleep efficiency)",
        "core and skin temperature",
        "thermal comfort and perceptual scales"
      ],
      "total": 12
    },
    {
      "name": "Languages",
      "items": [
        "English (native)"
      ],
      "total": 1
    }
  ],
  "headline": {
    "participants": 122,
    "personNights": 10303,
    "fieldWaves": 3,
    "programmes": 2,
    "reviewsInProgress": 4,
    "publications": 11
  }
};
