#!/usr/bin/env python3
"""
Bake the RPG page's content into rpg/data.js.

Reads two sources and nothing else:
  - references.bib (generated from ORCID; already public)
  - the TECHNICAL & METHODOLOGICAL SKILLS section of the private CV Markdown

The CV is read WHITELIST-ONLY: this script extracts the five skill-category
lines from that one section and never copies any other part of the file. That
is deliberately stricter than the blacklist redaction in build-cv-pdf.py —
the game needs so little that everything else can simply stay unread.

Headline numbers are constants below; they mirror what index.qmd already says
in public. Update them on the February/August CV cadence.

As a tripwire, the finished output is scanned for private strings (phone
fragments, residency status, the withheld Sport Singapore review) and the
script fails loudly if any appear. Prints every extraction it performs.

    python3 tools/build-rpg-data.py
"""

import json
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
BIB = ROOT / "references.bib"
CV = Path.home() / "Documents" / "Professional" / "cv" / "current" / "master-cv.md"
OUT = ROOT / "rpg" / "data.js"

# Public headline numbers — must match what index.qmd already states.
HEADLINE = {
    "participants": 122,
    "personNights": 10303,
    "fieldWaves": 3,
    "programmes": 2,
    "reviewsInProgress": 4,
}

# Nothing below these strings may ever reach the public output.
TRIPWIRES = ["8058", "9233", "Permanent Resident", "SEA Games", "Sport Singapore"]

MAX_SKILL_ITEMS = 4  # per category; the full list stays on the CV page


def parse_bib(text):
    """references.bib is machine-generated and regular: one @article per
    block, one `field = {value}` per line."""
    pubs = []
    for block in re.split(r"@article\{", text)[1:]:
        fields = dict(re.findall(r"^\s*(\w+)\s*=\s*\{(.*)\},?\s*$", block, re.MULTILINE))
        authors = [a.strip() for a in fields.get("author", "").split(" and ")]
        surnames = [a.split(",")[0].strip() for a in authors if a.strip()]
        if len(surnames) > 3:
            authors_short = f"{surnames[0]} et al."
        else:
            authors_short = ", ".join(surnames)
        pubs.append({
            "authorsShort": authors_short,
            "nAuthors": len(surnames),
            "year": int(fields.get("year", 0)),
            "title": fields.get("title", "").strip(),
            "journal": fields.get("journal", "").strip(),
            "doi": fields.get("doi", "").strip(),
        })
    pubs.sort(key=lambda p: (-p["year"], p["authorsShort"]))
    return pubs


def parse_skills(text):
    """Whitelist extraction: only the five `**Category** — items` lines inside
    the TECHNICAL & METHODOLOGICAL SKILLS section are read."""
    m = re.search(
        r"^##\s+TECHNICAL & METHODOLOGICAL SKILLS\s*$(.*?)(?=^##\s|\Z)",
        text, re.MULTILINE | re.DOTALL,
    )
    if not m:
        sys.exit("could not find the TECHNICAL & METHODOLOGICAL SKILLS section")
    skills = []
    for cat, items in re.findall(r"^\*\*(.+?)\*\*\s+—\s+(.+)$", m.group(1), re.MULTILINE):
        # strip markdown links: [text](url) -> text
        items = re.sub(r"\[([^\]]+)\]\([^)]+\)", r"\1", items)
        parts = [p.strip().rstrip(".") for p in items.split(";") if p.strip()]
        skills.append({
            "name": cat.strip(),
            "items": parts[:MAX_SKILL_ITEMS],
            "total": len(parts),
        })
    if len(skills) != 5:
        sys.exit(f"expected 5 skill categories, found {len(skills)}")
    return skills


def main():
    pubs = parse_bib(BIB.read_text(encoding="utf-8"))
    print(f"publications: {len(pubs)} entries from {BIB.name}")
    for p in pubs:
        print(f"  {p['year']}  {p['authorsShort']}: {p['title'][:60]}…")

    skills = parse_skills(CV.read_text(encoding="utf-8"))
    print(f"skills: {len(skills)} categories from {CV.name} (whitelist-only)")
    for s in skills:
        print(f"  {s['name']}: {len(s['items'])} of {s['total']} items")

    data = {
        "publications": pubs,
        "skills": skills,
        "headline": {**HEADLINE, "publications": len(pubs)},
    }
    js = (
        "// GENERATED by tools/build-rpg-data.py — do not edit by hand.\n"
        "window.RPG_DATA = "
        + json.dumps(data, ensure_ascii=False, indent=2)
        + ";\n"
    )

    for needle in TRIPWIRES:
        if needle.lower() in js.lower():
            sys.exit(f"TRIPWIRE: private string {needle!r} found in output — aborting, nothing written")

    OUT.write_text(js, encoding="utf-8")
    print(f"wrote {OUT.relative_to(ROOT)}  ({len(js):,} bytes; tripwire clean)")


if __name__ == "__main__":
    main()
